# 서버 설정
server:
  port: 8080

# 스프링 관련 설정
spring:
  profiles:
    active: local
  # 데이터소스(DB) 설정
  datasource:
    url: jdbc:h2:mem:testdb # 테스트용 DB는 보통 testdb 라는 이름을 씁니다.
#    url: jdbc:h2:tcp://localhost/~/maintenance
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 콘솔 웹 접근 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 및 Hibernate 설정
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

  # Spring Boot DevTools 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# 로깅 설정 (최상위 레벨)
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace